on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: write

    steps:
      - run: |
          curl -LO https://code.videolan.org/videolan/vlc-ios/-/archive/master/vlc-ios-master.tar.gz
          tar -xf vlc-ios-master.tar.gz

      - working-directory: vlc-ios-master
        run: |
          pod install

      - working-directory: vlc-ios-master
        run: |
          xcodebuild -workspace VLC.xcworkspace -scheme VLC-iOS-no-watch -configuration Release -derivedDataPath ../DerivedData CODE_SIGNING_ALLOWED=NO

      - run: |
          mkdir Payload
          cp -R DerivedData/Build/Products/Release-iphoneos/VLC-iOS-no-watch.app Payload
          zip -r VLC.ipa Payload

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create vlc VLC.ipa --draft --repo $GITHUB_REPOSITORY
