on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: write

    steps:
      - run: |
          curl -LO https://code.videolan.org/videolan/vlc-ios/-/archive/master/vlc-ios-master.tar.gz
          tar -xf vlc-ios-master.tar.gz

      - working-directory: vlc-ios-master
        run: |
          pod install

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24

      # - working-directory: vlc-ios-master
      #   run: |
      #     xcodebuild -workspace VLC.xcworkspace -scheme VLC-iOS -configuration Release CODE_SIGNING_ALLOWED=NO -derivedDataPath ./DerivedData

      # - working-directory: vlc-ios-master
      #   run: |
      #     mkdir Payload
      #     cp -R "./DerivedData/Build/Products/Release-iphoneos/VLC for iOS.app" Payload/
      #     zip -r VLC.ipa Payload/

      - working-directory: vlc-ios-master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create vlc VLC.ipa --draft --repo $GITHUB_REPOSITORY
